name: gerencianet_webhook_example
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  dio: ^4.0.0
  dio_http2_adapter: ^2.0.0
  shelf: ^1.1.4
  shelf_router: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
